module.exports = {
    SPOONACULAR_API_URL: process.env.SPOONACULAR_API_URL,
    SPOONACULAR_API_KEY: process.env.SPOONACULAR_API_KEY,
    SPOONACULAR_API_HASH: process.env.SPOONACULAR_API_HASH,
    SPOONACULAR_API_USERNAME: process.env.SPOONACULAR_API_USERNAME,
}
